# Copyright(C) 2025-2026 Advanced Micro Devices, Inc. All rights reserved.
# SPDX-License-Identifier: MIT

name: 'Start Lemonade Server'
description: 'Starts Lemonade server, pulls models, and loads them for testing'

inputs:
  model-name:
    description: 'Primary model to pull and load'
    required: false
    default: 'Qwen3-4B-Instruct-2507-GGUF'
  additional-models:
    description: 'Comma-separated list of additional models to pull (but not load)'
    required: false
    default: ''
  port:
    description: 'Server port'
    required: false
    default: '8000'
  ctx-size:
    description: 'Context size'
    required: false
    default: '32768'
  init-wait-time:
    description: 'Seconds to wait after loading model'
    required: false
    default: '10'
  clear-cache:
    description: 'Clear model cache before pulling'
    required: false
    default: 'false'

outputs:
  process-id:
    description: 'Lemonade server process ID'
    value: ${{ steps.start.outputs.lemonade-process-id }}

runs:
  using: 'composite'
  steps:
    - name: Set UTF-8 encoding
      shell: bash
      run: |
        echo "PYTHONIOENCODING=utf-8" >> $GITHUB_ENV
        echo "PYTHONUTF8=1" >> $GITHUB_ENV

    - name: Start Lemonade Server (Windows)
      id: start-windows
      if: runner.os == 'Windows'
      shell: powershell
      env:
        PYTHONIOENCODING: utf-8
        PYTHONUTF8: '1'
      run: |
        # Set console to UTF-8
        [Console]::OutputEncoding = [System.Text.Encoding]::UTF8
        chcp 65001 | Out-Null

        $scriptPath = "${{ github.workspace }}\scripts\start-lemonade.ps1"

        $params = @{
          ModelName = "${{ inputs.model-name }}"
          Port = [int]"${{ inputs.port }}"
          CtxSize = [int]"${{ inputs.ctx-size }}"
          InitWaitTime = [int]"${{ inputs.init-wait-time }}"
        }

        if ("${{ inputs.additional-models }}" -ne "") {
          $params.AdditionalModels = "${{ inputs.additional-models }}"
        }

        if ("${{ inputs.clear-cache }}" -eq "true") {
          $params.ClearCache = $true
        }

        & $scriptPath @params

        # Export process ID if set by script
        if ($env:LEMONADE_PROCESS_ID) {
          echo "lemonade-process-id=$env:LEMONADE_PROCESS_ID" >> $env:GITHUB_OUTPUT
        }

    - name: Start Lemonade Server (Linux)
      id: start-linux
      if: runner.os == 'Linux'
      shell: bash
      env:
        PYTHONIOENCODING: utf-8
        PYTHONUTF8: '1'
      run: |
        chmod +x "${{ github.workspace }}/scripts/start-lemonade.sh"

        ARGS="--model-name ${{ inputs.model-name }}"
        ARGS="$ARGS --port ${{ inputs.port }}"
        ARGS="$ARGS --ctx-size ${{ inputs.ctx-size }}"
        ARGS="$ARGS --init-wait-time ${{ inputs.init-wait-time }}"

        if [ -n "${{ inputs.additional-models }}" ]; then
          ARGS="$ARGS --additional-models '${{ inputs.additional-models }}'"
        fi

        if [ "${{ inputs.clear-cache }}" = "true" ]; then
          ARGS="$ARGS --clear-cache"
        fi

        eval "${{ github.workspace }}/scripts/start-lemonade.sh $ARGS"

        # Export process ID if set by script
        if [ -n "$LEMONADE_PROCESS_ID" ]; then
          echo "lemonade-process-id=$LEMONADE_PROCESS_ID" >> $GITHUB_OUTPUT
        fi

    - name: Consolidate output
      id: start
      shell: bash
      run: |
        # Get process ID from whichever platform ran
        if [ -n "${{ steps.start-windows.outputs.lemonade-process-id }}" ]; then
          echo "lemonade-process-id=${{ steps.start-windows.outputs.lemonade-process-id }}" >> $GITHUB_OUTPUT
        elif [ -n "${{ steps.start-linux.outputs.lemonade-process-id }}" ]; then
          echo "lemonade-process-id=${{ steps.start-linux.outputs.lemonade-process-id }}" >> $GITHUB_OUTPUT
        fi
