[tool.black]
line-length = 88
target-version = ['py37']
exclude = '''
(
  /(
    | \.eggs
    | \.git
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | _build
    | buck-out
  )/
  | src/gaia/interface/rc_resource\.py
  | src/gaia/interface/ui_form\.py
)
'''