from setuptools import setup

ipex_version = "2.2.0"

setup(
    name="gaia",
    version="0.1.0",
    description="GAIA genAI sandbox",
    author="Kalin Ovtcharov",
    author_email="kalin.ovtcharov@amd.com",
    package_dir={"": "src"},
    packages=[
        "gaia",
        "gaia.llm",
        "gaia.agents",
        "gaia.agents.Clipy",
        "gaia.agents.Datalin",
        "gaia.agents.Joker",
        "gaia.agents.Neo",
        "gaia.agents.Picasso",
    ],
    install_requires=[
        "botbuilder-integration-aiohttp>=4.14.0",
        "botbuilder-core",
        "aiohttp",
        "fastapi",
        "pydantic",
        "uvicorn",
        "openai",
        "matplotlib",
        "transformers",
        "torch",
        "pandas",
        "onnx",
        "accelerate",
        "llama_index",
        "websockets",
        "websocket-client",
        "wordcloud",
        "python-dotenv",
        "torch",
        "torchvision",
        "torchaudio",
        "llama-index-readers-youtube-transcript",
        "llama-index-readers-github",
        "llama-index-embeddings-huggingface",
    ],
    extras_require={
        "cuda": [
            "torch @ https://download.pytorch.org/whl/cu118/torch-1.13.1%2Bcu118-cp38-cp38-linux_x86_64.whl",
            "torchvision @ https://download.pytorch.org/whl/cu118/torchvision-0.14.1%2Bcu118-cp38-cp38-linux_x86_64.whl",
            "torchaudio @ https://download.pytorch.org/whl/cu118/torchaudio-0.13.1%2Bcu118-cp38-cp38-linux_x86_64.whl",
        ],
    },
    classifiers=[],
    python_requires=">=3.8, <3.12",
    long_description=open("README.md", "r", encoding="utf-8").read(),
    long_description_content_type="text/markdown",
    include_package_data=True,
)
