// Copyright(C) 2025-2026 Advanced Micro Devices, Inc. All rights reserved.
// SPDX-License-Identifier: MIT

/**
 * Shared types for the Agent Hub Worker.
 *
 * The JSON shapes here mirror the `gaia-agent.yaml` manifest format documented
 * in `docs/spec/agent-hub-restructure.mdx` and parsed by
 * `src/gaia/hub/manifest.py`. Field names are kept identical so the catalog the
 * Worker serves can be consumed by the same code that reads the source manifest.
 */

/**
 * Catalog lane discriminator. `agent | app | component` shipped with #1716;
 * `skill` is the marketplace lane (#2467) — a `SKILL.md` (± `tools.py`) bundle
 * published and installed on its own, not a runnable package.
 */
export type PackageType = "agent" | "app" | "component" | "skill";

/** Worker runtime bindings (see wrangler.toml). */
export interface Env {
  /** R2 bucket holding the catalog, per-agent manifests, and artifacts. */
  BUCKET: R2Bucket;
  /**
   * JSON map of publish token -> publisher record. Set as a secret:
   *   wrangler secret put PUBLISH_TOKENS
   * Shape: { "<token>": { "publisher": "AMD", "authors": ["AMD"] } }
   * An author entry of "*" grants publishing for any author value.
   */
  PUBLISH_TOKENS?: string;

  /**
   * Bearer token for the maintainer-only `POST /reindex` endpoint, which
   * rebuilds index.json from the immutable R2 objects (idempotent). Separate
   * from PUBLISH_TOKENS so a reindex never needs a publish credential.
   * Set with `wrangler secret put REINDEX_TOKEN`.
   */
  REINDEX_TOKEN?: string;
  /** Max artifact size in bytes (string in wrangler vars). */
  MAX_ARTIFACT_BYTES?: string;
}

/** A publisher resolved from a bearer token. */
export interface Publisher {
  /** Display/identity name recorded against each published version. */
  publisher: string;
  /** Author values this token may publish under ("*" means any). */
  authors: string[];
}

/**
 * The `requirements:` block as stored in per-agent manifests. Numbers default
 * to 0 and `npu` to false when the uploaded gaia-agent.yaml omits them, so the
 * stored shape is always fully populated.
 */
export interface Requirements {
  platforms: string[];
  min_memory_gb: number;
  min_disk_gb: number;
  min_context_size: number;
  npu: boolean;
  gpu_vram_gb: number;
}

export interface Interfaces {
  tui?: boolean;
  cli?: boolean;
  pipe?: boolean;
  api_server?: boolean;
  mcp_server?: boolean;
}

/**
 * A validated manifest parsed from an uploaded `gaia-agent.yaml`. Only the
 * fields the Worker needs to gate publishing and build the catalog are typed;
 * the canonical/full validation lives in `src/gaia/hub/manifest.py`.
 */
export interface ParsedManifest {
  id: string;
  name: string;
  version: string;
  description: string;
  author: string;
  license: string;
  language: string;
  /**
   * Package kind: agent | app | component. Defaults to "agent" (#1716).
   * `skill` is deliberately NOT accepted here — skills are published from a
   * `SKILL.md` through POST /publish/skill, not from a gaia-agent.yaml (#2467).
   */
  type: string;
  category: string;
  tags: string[];
  icon: string;
  security_tier: string;
  min_gaia_version?: string;
  models: string[];
  tools_count: number;
  permissions: string[];
  requirements: Requirements;
  interfaces: Interfaces;
  deprecated: boolean;
  deprecation_message?: string;
  npm_package?: string;
  playground_url?: string;
}

/** Metadata for one stored artifact (computed server-side). */
export interface ArtifactInfo {
  filename: string;
  /** R2 object key: agents/<id>/<version>/<filename>. */
  path: string;
  size_bytes: number;
  /** Lowercase hex SHA-256 generated by the Worker, never trusted from input. */
  sha256: string;
  content_type: string;
}

/**
 * One published version inside a per-agent manifest.
 *
 * A version may carry MORE THAN ONE artifact — one per platform for a native
 * binary release (e.g. the frozen email agent ships win32-x64, darwin-arm64,
 * darwin-x64, linux-x64 under a single `0.1.0`). `artifacts` is the complete
 * set; `artifact` is the primary (first-published) entry kept for catalog
 * display and backward compatibility with single-artifact (wheel) agents.
 *
 * Within a version the artifact set is APPEND-ONLY per distinct filename:
 * adding a new platform binary is allowed, but re-uploading an existing
 * filename is rejected (immutability / tamper guard).
 */
export interface VersionEntry {
  version: string;
  published_at: string;
  publisher: string;
  deprecated: boolean;
  /** Primary artifact (first published for this version). */
  artifact: ArtifactInfo;
  /** All artifacts published under this version (one per platform). */
  artifacts: ArtifactInfo[];
}

/**
 * Per-agent manifest stored at `agents/<id>/manifest.json`. Aggregates full
 * metadata plus every published version. Source of truth for immutability.
 */
export interface AgentManifest {
  id: string;
  name: string;
  description: string;
  author: string;
  license: string;
  language: string;
  /** Package kind: agent | app | component. Defaults to "agent" (#1716). */
  type: string;
  category: string;
  tags: string[];
  icon: string;
  security_tier: string;
  min_gaia_version?: string;
  models: string[];
  tools_count: number;
  permissions: string[];
  requirements: Requirements;
  interfaces: Interfaces;
  latest_version: string;
  deprecated: boolean;
  deprecation_message?: string;
  npm_package?: string;
  playground_url?: string;
  versions: Record<string, VersionEntry>;
}

// ── Skills lane (#2467) ─────────────────────────────────────────────────────
// A skill is published from its `SKILL.md` front matter, whose grammar is
// `docs/plans/skill-format.mdx`: the Agent Skills standard base (name,
// description, license, version) plus the GAIA-owned `metadata.gaia` namespace.
// Skills live under their own R2 prefix (`skills/`) but share the catalog, so
// the marketplace is a fourth lane of the existing hub, not a second registry.

/**
 * One `@tool` declaration a skill PROVIDES (`metadata.gaia.tools`). Distinct
 * from `tools_required`, which names registry tools the skill CONSUMES — the
 * skill-format spec locks that distinction, so never collapse the two.
 */
export interface SkillToolDecl {
  name: string;
  /** "" when the declaration omits one. */
  description: string;
}

/**
 * `metadata.gaia.requirements` — the skill's own constraint block. Unrelated to
 * the agent-lane {@link Requirements} (memory/disk/platforms): a skill declares
 * model/context/runtime/dependency constraints instead. Always fully populated
 * ("" / [] for unset) so the stored shape is stable.
 */
export interface SkillRequirements {
  /** Minimum parameter count, e.g. ">=7B" (advisory). */
  model: string;
  /** Minimum context window, e.g. ">=8K". */
  context: string;
  /** Python constraint, e.g. ">=3.10". */
  python: string;
  dependencies: string[];
  node_dependencies: string[];
  env_vars: string[];
  hardware: SkillHardware;
}

/** `metadata.gaia.requirements.hardware`; "" when unset. */
export interface SkillHardware {
  /** e.g. "required" | "optional". */
  npu: string;
  /** e.g. ">=8GB". */
  gpu_vram: string;
}

/**
 * The pre-publish security-audit result recorded against a published skill
 * (#2468). Only cleared publishes reach the catalog, so the stored verdict is
 * either "ALLOW" (a report cleared the gate) or "unaudited" (the tier's gate is
 * advisory and no report was supplied) — BLOCK/REVIEW are rejected at publish
 * and never written. See `audit.ts`.
 */
export interface SkillAuditRecord {
  verdict: "ALLOW" | "unaudited";
  /** Audit engine id + version from the report, e.g. "gaia-skill-audit/0.1.0"; "" when unaudited. */
  engine: string;
  /** ISO-8601 timestamp the report was produced; "" when unaudited. */
  audited_at: string;
  /** Number of non-blocking findings the report surfaced. */
  findings: number;
}

/**
 * A validated `SKILL.md` front matter block. Mirrors the field reference in
 * `docs/plans/skill-format.mdx`; the canonical loader-side validation is
 * `src/gaia/skills/` (#888).
 */
export interface ParsedSkillManifest {
  name: string;
  version: string;
  description: string;
  /** "" when the front matter omits it. */
  license: string;
  security_tier: string;
  permissions: string[];
  tools: SkillToolDecl[];
  tools_required: string[];
  requirements: SkillRequirements;
}

/**
 * Per-skill manifest stored at `skills/<name>/manifest.json`. The skill-lane
 * counterpart of {@link AgentManifest}: same aggregate-plus-versions shape, so
 * immutability, ownership, and version resolution work identically. Install-time
 * artifact verification reads `versions[v].artifact.sha256` from here, exactly
 * as the agent lane does.
 */
export interface SkillManifest {
  name: string;
  description: string;
  /** Publisher identity resolved from the publish token — a skill's provenance. */
  author: string;
  license: string;
  security_tier: string;
  permissions: string[];
  tools: SkillToolDecl[];
  tools_required: string[];
  requirements: SkillRequirements;
  audit: SkillAuditRecord;
  latest_version: string;
  versions: Record<string, VersionEntry>;
}

/**
 * Skill-only catalog fields, nested so the flat {@link IndexEntry} keys keep
 * their agent-lane meaning for every existing reader. `security_tier` and
 * `permissions` are NOT duplicated here — they are already top-level and carry
 * the same meaning in both lanes.
 *
 * Named `skill_metadata` rather than `skill` because `IndexEntry.skill` is
 * already taken by an agent's SKILL.md playbook markdown.
 */
export interface SkillMetadata {
  /** Typed `@tool` declarations the skill provides. */
  tools: SkillToolDecl[];
  /** Registry tool names the skill consumes (the #887/#1451 recipe contract). */
  tools_required: string[];
  /** Skill-shaped requirements (model/context/deps/env/hardware). */
  requirements: SkillRequirements;
  /** Pre-publish security-audit result (#2468). */
  audit: SkillAuditRecord;
}

/**
 * The `requirements` block in an index entry. Same numbers as
 * {@link Requirements} but `npu` is rendered as "required"/"optional" — the
 * shape the website Hub pages consume.
 */
export interface IndexRequirements {
  min_memory_gb: number;
  min_disk_gb: number;
  min_context_size: number;
  platforms: string[];
  npu: "required" | "optional";
  gpu_vram_gb: number;
}

/**
 * One entry in the top-level catalog index.json. This is the contract the
 * website Hub pages build from (`website/src/data/catalog.ts` `Agent`) — keep
 * the two in sync.
 */
export interface IndexEntry {
  id: string;
  name: string;
  description: string;
  category: string;
  latest_version: string;
  icon: string;
  language: string;
  /**
   * Catalog lane: agent | app | component (#1716) | skill (#2467). Defaults to
   * "agent". A reader that renders every entry as an installable agent MUST
   * filter on this — skills install through `gaia skill install`, not the agent
   * install path.
   */
  type: PackageType;
  author: string;
  security_tier: string;
  download_size_bytes: number;
  tags: string[];
  tools_count: number;
  models: string[];
  /** Empty string when the manifest does not declare one. */
  min_gaia_version: string;
  permissions: string[];
  deprecated: boolean;
  deprecation_message?: string;
  requirements: IndexRequirements;
  /** README.md markdown of the latest version; empty string if none was published. */
  readme: string;
  /** CHANGELOG.md markdown of the latest version; empty string if none was published. */
  changelog: string;
  /** SPEC.md (technical reference) markdown of the latest version; "" if none was published. */
  spec: string;
  /** SKILL.md (AI-integration playbook) markdown of the latest version; "" if none was published. */
  skill: string;
  /** EVALUATION.md (evaluation guide) markdown of the latest version; "" if none was published. */
  evaluation: string;
  /** CAPABILITY_MATRIX.md markdown of the latest version; "" if none was published. */
  capability_matrix: string;
  /**
   * Eval-scorecard markdown (SCORECARD.md body, YAML front matter stripped) of the
   * latest version, rendered as its own doc tab on the hub page; "" if none was
   * published. The machine-readable aggregate lives in `eval_score`, and the
   * canonical source in `eval_scorecard_url`.
   */
  scorecard: string;
  /** npm package name when the agent is distributed via npm; absent otherwise. */
  npm_package?: string;
  /** Localhost playground URL served by the agent's sidecar; absent otherwise. */
  playground_url?: string;
  /** Public URL of the eval scorecard markdown for the latest version; absent when none was published. */
  eval_scorecard_url?: string;
  /** Aggregate eval score (0–100) parsed from the latest version's scorecard front matter; absent when none was published or parseable. */
  eval_score?: number;
  /**
   * Whole-package download: a single zip (all platform binaries + client + docs)
   * plus its file listing. Present only when a `package_files` manifest was
   * published for the latest version.
   */
  package?: PackageInfo;
  /**
   * Skill-lane fields (#2467). Present only on `type: "skill"` entries; absent
   * everywhere else, so agent-lane readers are untouched.
   */
  skill_metadata?: SkillMetadata;
}

/** One file inside the whole-package zip (for the hub's file-list display). */
export interface PackageFile {
  name: string;
  size_bytes: number;
}

/** The downloadable whole-package zip + its contents. */
export interface PackageInfo {
  /** Zip artifact filename, e.g. "agent-email-0.2.1.zip" (downloaded from the version dir). */
  filename: string;
  /** Zip size in bytes; 0 if the artifact isn't found. */
  size_bytes: number;
  /** Files contained in the zip (sorted), for the hub's file list. */
  files: PackageFile[];
}

/**
 * The top-level catalog served at GET /index.json.
 *
 * Every lane — agents, apps, components, and skills (#2467) — lives in the one
 * `agents` array, discriminated by {@link IndexEntry.type}. The key keeps its
 * historical name so every published consumer keeps parsing the catalog
 * unchanged; lane segmentation is a filter, not a second array.
 */
export interface CatalogIndex {
  schema_version: number;
  generated_at: string;
  agents: IndexEntry[];
}
