// Copyright(C) 2025-2026 Advanced Micro Devices, Inc. All rights reserved.
// SPDX-License-Identifier: MIT

/**
 * Shared types for the Agent Hub Worker.
 *
 * The JSON shapes here mirror the `gaia-agent.yaml` manifest format documented
 * in `docs/spec/agent-hub-restructure.mdx` and parsed by
 * `src/gaia/hub/manifest.py`. Field names are kept identical so the catalog the
 * Worker serves can be consumed by the same code that reads the source manifest.
 */

/** Worker runtime bindings (see wrangler.toml). */
export interface Env {
  /** R2 bucket holding the catalog, per-agent manifests, and artifacts. */
  BUCKET: R2Bucket;
  /**
   * JSON map of publish token -> publisher record. Set as a secret:
   *   wrangler secret put PUBLISH_TOKENS
   * Shape: { "<token>": { "publisher": "AMD", "authors": ["AMD"] } }
   * An author entry of "*" grants publishing for any author value.
   */
  PUBLISH_TOKENS?: string;
  /** Max artifact size in bytes (string in wrangler vars). */
  MAX_ARTIFACT_BYTES?: string;
}

/** A publisher resolved from a bearer token. */
export interface Publisher {
  /** Display/identity name recorded against each published version. */
  publisher: string;
  /** Author values this token may publish under ("*" means any). */
  authors: string[];
}

/** The subset of the `requirements:` block surfaced in the catalog. */
export interface Requirements {
  platforms: string[];
  min_memory_gb?: number;
  min_disk_gb?: number;
  min_context_size?: number;
  npu?: boolean;
  gpu_vram_gb?: number;
}

export interface Interfaces {
  tui?: boolean;
  cli?: boolean;
  pipe?: boolean;
  api_server?: boolean;
  mcp_server?: boolean;
}

/**
 * A validated manifest parsed from an uploaded `gaia-agent.yaml`. Only the
 * fields the Worker needs to gate publishing and build the catalog are typed;
 * the canonical/full validation lives in `src/gaia/hub/manifest.py`.
 */
export interface ParsedManifest {
  id: string;
  name: string;
  version: string;
  description: string;
  author: string;
  license: string;
  language: string;
  category: string;
  tags: string[];
  icon: string;
  security_tier: string;
  min_gaia_version?: string;
  models: string[];
  requirements: Requirements;
  interfaces: Interfaces;
  deprecated: boolean;
}

/** Metadata for one stored artifact (computed server-side). */
export interface ArtifactInfo {
  filename: string;
  /** R2 object key: agents/<id>/<version>/<filename>. */
  path: string;
  size_bytes: number;
  /** Lowercase hex SHA-256 generated by the Worker, never trusted from input. */
  sha256: string;
  content_type: string;
}

/** One published version inside a per-agent manifest. */
export interface VersionEntry {
  version: string;
  published_at: string;
  publisher: string;
  deprecated: boolean;
  artifact: ArtifactInfo;
}

/**
 * Per-agent manifest stored at `agents/<id>/manifest.json`. Aggregates full
 * metadata plus every published version. Source of truth for immutability.
 */
export interface AgentManifest {
  id: string;
  name: string;
  description: string;
  author: string;
  license: string;
  language: string;
  category: string;
  tags: string[];
  icon: string;
  security_tier: string;
  min_gaia_version?: string;
  models: string[];
  requirements: Requirements;
  interfaces: Interfaces;
  latest_version: string;
  deprecated: boolean;
  versions: Record<string, VersionEntry>;
}

/** One lightweight entry in the top-level catalog index.json. */
export interface IndexEntry {
  id: string;
  name: string;
  description: string;
  category: string;
  latest_version: string;
  icon: string;
  language: string;
  author: string;
  security_tier: string;
  download_size_bytes: number;
  requirements: { platforms: string[] };
  deprecated: boolean;
}

/** The top-level catalog served at GET /index.json. */
export interface CatalogIndex {
  schema_version: number;
  generated_at: string;
  agents: IndexEntry[];
}
