name: Build GAIA Apps (Release)

on:
  workflow_call:
    inputs:
      release_tag:
        description: 'Release tag to use'
        required: true
        type: string
      draft:
        description: 'Create as draft release'
        required: false
        type: boolean
        default: false

jobs:
  placeholder:
    runs-on: ubuntu-latest
    steps:
      - name: Placeholder
        run: |
          echo "Placeholder for app release builds - actual implementation in PR #761"
          echo "Release tag: ${{ inputs.release_tag }}"
          echo "Draft: ${{ inputs.draft }}"