# Copyright(C) 2025-2026 Advanced Micro Devices, Inc. All rights reserved.
# SPDX-License-Identifier: MIT
"""Keeps the published eval score identical everywhere it is quoted.

``SCORECARD.md`` is machine-generated by ``packaging/gen_scorecard.py`` from a
real eval run; its ``aggregate.value`` front-matter field is the single source
of truth. ``README.md`` and ``EVALUATION.md`` quote that number in prose, and
prose does not regenerate — so a fresh eval bumped the scorecard to 84.53 while
both narrative docs kept advertising the 0.3.0-era 83.4. The package shipped
two different scores for the same version, which is exactly the failure mode the
"one functional change updates every doc" rule exists to prevent.

Scope note: ``CHANGELOG.md`` is deliberately NOT checked. Its per-version
entries are a historical record — the 83.4 under ``## 0.3.0`` was true then and
rewriting it would falsify the release history.
"""

from __future__ import annotations

import re
from pathlib import Path

import pytest

yaml = pytest.importorskip("yaml")

# tests/ -> python/ -> email/ ; the npm package sits beside python/.
_NPM_ROOT = Path(__file__).resolve().parents[2] / "npm"
_SCORECARD = _NPM_ROOT / "SCORECARD.md"

# Prose docs that describe the CURRENT agent and therefore must quote the
# current aggregate. Any "NN.N / 100" or "NN.NN / 100" in these is a score claim.
_PROSE_DOCS = ("README.md", "EVALUATION.md")

_SCORE_CLAIM = re.compile(r"(\d+\.\d+)\s*/\s*100")


def _front_matter(path: Path) -> dict:
    text = path.read_text(encoding="utf-8")
    match = re.match(r"^---\n(.*?)\n---\n", text, re.DOTALL)
    assert match, f"{path.name} has no YAML front matter"
    return yaml.safe_load(match.group(1))


@pytest.fixture(scope="module")
def aggregate_value() -> float:
    data = _front_matter(_SCORECARD)
    value = data.get("aggregate", {}).get("value")
    assert isinstance(value, (int, float)), (
        "SCORECARD.md front matter has no numeric aggregate.value; "
        "regenerate it with packaging/gen_scorecard.py"
    )
    return float(value)


def test_scorecard_body_matches_its_own_front_matter(aggregate_value):
    """The generated body must not disagree with the generated front matter."""
    body = _SCORECARD.read_text(encoding="utf-8")
    assert f"**Aggregate score: {aggregate_value}**" in body, (
        f"SCORECARD.md front matter says aggregate.value={aggregate_value} but "
        "the rendered body quotes a different number — regenerate it."
    )


@pytest.mark.parametrize("doc_name", _PROSE_DOCS)
def test_prose_docs_quote_the_current_aggregate(doc_name, aggregate_value):
    """Every 'NN.NN / 100' claim in the prose docs is the current score."""
    path = _NPM_ROOT / doc_name
    claims = _SCORE_CLAIM.findall(path.read_text(encoding="utf-8"))
    assert claims, (
        f"{doc_name} quotes no score at all — it is supposed to advertise the "
        "eval result; did the wording change without updating this guard?"
    )
    stale = sorted({c for c in claims if float(c) != aggregate_value})
    assert not stale, (
        f"{doc_name} advertises score(s) {stale} but SCORECARD.md's current "
        f"aggregate is {aggregate_value}. Update the prose whenever the eval is "
        "re-run — a package that ships two different scores for one version is "
        "not trustworthy."
    )
