#!/usr/bin/env python3
"""Extract Archivo + Hanken Grotesk @font-face blocks from the reference template
bundle and emit a self-contained assets/fonts.css with base64 woff2 data URIs.

The template stores font bytes in its <script type="__bundler/manifest"> tag (base64,
optionally gzip-compressed) keyed by uuid, and references them as url("<uuid>") inside
@font-face blocks in its <script type="__bundler/template"> tag.
"""
import base64
import gzip
import json
import re
import sys
from pathlib import Path

KEEP_FAMILIES = {"Archivo", "Hanken Grotesk"}  # brand identity; code uses system mono

def main() -> int:
    template = Path(sys.argv[1]) if len(sys.argv) > 1 else Path("/Users/tomasz/Public/gaia-roadmap.html")
    out = Path(__file__).resolve().parent.parent / "assets" / "fonts.css"

    html = template.read_text(encoding="utf-8")
    manifest = json.loads(re.search(r'<script type="__bundler/manifest">(.*?)</script>', html, re.S).group(1))
    tpl = json.loads(re.search(r'<script type="__bundler/template">(.*?)</script>', html, re.S).group(1))

    blocks = re.findall(r'@font-face\s*\{.*?\}', tpl, re.S)
    if not blocks:
        print("FAIL: no @font-face blocks found", file=sys.stderr)
        return 1

    emitted, seen_uuids = [], set()
    for block in blocks:
        fam_m = re.search(r"font-family:\s*'([^']+)'", block)
        uuid_m = re.search(r'src:\s*url\("([^"]+)"\)', block)
        if not fam_m or not uuid_m:
            continue
        family, uuid = fam_m.group(1), uuid_m.group(1)
        if family not in KEEP_FAMILIES or uuid not in manifest:
            continue
        entry = manifest[uuid]
        raw = base64.b64decode(entry["data"])
        if entry.get("compressed"):
            raw = gzip.decompress(raw)
        b64 = base64.b64encode(raw).decode("ascii")
        block = block.replace(f'url("{uuid}")', f'url(data:font/woff2;base64,{b64})')
        emitted.append(block)
        seen_uuids.add(uuid)

    if not emitted:
        print("FAIL: no Archivo/Hanken faces embedded", file=sys.stderr)
        return 1

    out.parent.mkdir(parents=True, exist_ok=True)
    header = "/* Generated by tools/build_fonts.py — Archivo + Hanken Grotesk, base64 woff2, offline. */\n"
    out.write_text(header + "\n".join(emitted) + "\n", encoding="utf-8")
    kb = out.stat().st_size / 1024
    print(f"PASS: wrote {out} — {len(emitted)} faces, {len(seen_uuids)} unique fonts, {kb:.0f} KB")
    return 0

if __name__ == "__main__":
    raise SystemExit(main())
