# Copyright(C) 2025-2026 Advanced Micro Devices, Inc. All rights reserved.
# SPDX-License-Identifier: MIT

name: 'Install Lemonade Server'
description: 'Verifies Lemonade Server is available and exports its path'

# Note: This action uses the pre-installed lemonade-server on the runner.
# It does NOT install a new version to avoid conflicts.

outputs:
  lemonade-path:
    description: 'Full path to the lemonade-server executable'
    value: ${{ steps.verify.outputs.lemonade_path }}

runs:
  using: 'composite'
  steps:
    - name: Get Expected Lemonade Version
      shell: powershell
      run: |
        # Import directly from version module to avoid triggering gaia/__init__.py
        $lemonadeVersion = python -c "import sys; sys.path.insert(0, 'src/gaia'); from version import LEMONADE_VERSION; print(LEMONADE_VERSION)"
        echo "LEMONADE_VERSION=$lemonadeVersion" >> $env:GITHUB_ENV
        Write-Host "Expected Lemonade version: $lemonadeVersion"

    - name: Verify Lemonade Server
      id: verify
      shell: powershell
      run: |
        Write-Host "=== Checking for Lemonade Server ==="

        # First check if it's already in PATH
        $lemonadeCmd = Get-Command lemonade-server -ErrorAction SilentlyContinue

        if (-not $lemonadeCmd) {
            Write-Host "lemonade-server not found in PATH, searching common installation locations..."

            # Common installation paths to check
            $searchPaths = @(
                "${env:ProgramFiles(x86)}\Lemonade Server\bin",
                "$env:ProgramFiles\Lemonade Server\bin",
                "$env:LOCALAPPDATA\Programs\Lemonade",
                "$env:ProgramFiles\Lemonade",
                "${env:ProgramFiles(x86)}\Lemonade",
                "$env:USERPROFILE\Lemonade",
                "$env:LOCALAPPDATA\Lemonade"
            )

            $lemonadePath = $null
            foreach ($path in $searchPaths) {
                $exePath = Join-Path $path "lemonade-server.exe"
                if (Test-Path $exePath) {
                    Write-Host "Found lemonade-server at: $exePath"
                    $lemonadePath = $exePath
                    # Add directory to PATH for this job
                    $dir = Split-Path $lemonadePath -Parent
                    Write-Host "Adding $dir to PATH"
                    echo "$dir" >> $env:GITHUB_PATH
                    $env:PATH = "$dir;$env:PATH"
                    break
                }
            }

            if (-not $lemonadePath) {
                Write-Host "ERROR: lemonade-server not found in any common location"
                Write-Host "Searched: $($searchPaths -join ', ')"
                Write-Host "Please ensure Lemonade Server is installed on this runner"
                exit 1
            }
        } else {
            $lemonadePath = $lemonadeCmd.Source
            Write-Host "Found lemonade-server in PATH at: $lemonadePath"
        }

        $versionOutput = & lemonade-server --version 2>&1
        Write-Host $versionOutput

        # Extract version and compare
        if ($versionOutput -match "(\d+\.\d+\.\d+)") {
            $installedVersion = $matches[1]
            Write-Host ""
            Write-Host "Installed version: $installedVersion"
            Write-Host "Expected version:  $env:LEMONADE_VERSION"

            if ($installedVersion -ne $env:LEMONADE_VERSION) {
                Write-Host ""
                Write-Host "WARNING: Version mismatch!"
                Write-Host "The runner has v$installedVersion but GAIA expects v$env:LEMONADE_VERSION"
                Write-Host "Tests will proceed with v$installedVersion"
            }
        }

        # Export path for use by other steps
        echo "lemonade_path=$lemonadePath" >> $env:GITHUB_OUTPUT
        echo "LEMONADE_SERVER_PATH=$lemonadePath" >> $env:GITHUB_ENV

        Write-Host ""
        Write-Host "Lemonade Server ready"
