# Copyright(C) 2024-2025 Advanced Micro Devices, Inc. All rights reserved.
# SPDX-License-Identifier: MIT

name: Build GAIA Installer

on:
  workflow_call:
    outputs:
      VERSION:
        description: "The extracted version number"
        value: ${{ jobs.build-installer.outputs.VERSION }}
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
    types: [opened, synchronize, reopened, ready_for_review]
  workflow_dispatch:

jobs:
  build-installer:
    runs-on: windows-latest
    if: github.event_name != 'pull_request' || github.event.pull_request.draft == false || contains(github.event.pull_request.labels.*.name, 'ready_for_ci')
    outputs:
      VERSION: ${{ steps.extract_version.outputs.VERSION }}
    steps:
      - uses: actions/checkout@v4

      - name: Install NSIS
        run: |
          # Download NSIS installer
          curl -L -o nsis.exe https://sourceforge.net/projects/nsis/files/NSIS%203/3.10/nsis-3.10-setup.exe

          # Install NSIS
          Start-Process nsis.exe -ArgumentList '/S' -Wait

      - name: Verify NSIS installation
        run: |
          # Check if NSIS is installed
          & 'C:\Program Files (x86)\NSIS\makensis.exe' /VERSION

      - name: Generate version.txt
        run: |
          python .\src\gaia\version.py

      - name: Extract version
        id: extract_version
        run: |
          $versionContent = Get-Content -Path "version.txt" -Raw
          $version = $versionContent -split '/' | Select-Object -Last 1
          $version = $version -split '\+' | Select-Object -First 1
          echo "VERSION=$version" >> $env:GITHUB_OUTPUT
          Write-Host "Extracted version: $version"

      - name: Build the GAIA installer
        run: |
          cd installer
          & 'C:\Program Files (x86)\NSIS\makensis.exe' /DOGA_TOKEN="${{ secrets.OGA_PUBLIC_TOKEN }}" 'Installer.nsi'

          if (Test-Path "gaia-setup.exe") {
            Write-Host "gaia-setup.exe has been created successfully."
          } else {
            Write-Host "gaia-setup.exe was not found."
            exit 1
          }

      - name: Upload Installer
        uses: actions/upload-artifact@v4
        with:
          name: gaia-windows-installer-${{ steps.extract_version.outputs.VERSION }}
          path: installer\gaia-setup.exe
          retention-days: 7