# Copyright(C) 2024-2025 Advanced Micro Devices, Inc. All rights reserved.
# SPDX-License-Identifier: MIT

# This workflow runs code quality checks (linting) for the entire codebase
# Provides fast feedback on code quality before running platform-specific tests
# Platform: Linux/Ubuntu (cross-platform code analysis)

name: Code Quality (Lint)

on:
  workflow_call:
  push:
    branches: ["main"]
    paths:
      - "src/**"
      - "tests/**"
      - "installer/**"
      - "groundtruth/**"
      - "test_data/**"
  pull_request:
    branches: ["main"]
    types: [opened, synchronize, reopened, ready_for_review]
    paths:
      - "src/**"
      - "tests/**"
      - "installer/**"
      - "groundtruth/**"
      - "test_data/**"
  merge_group:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  lint:
    name: Run Code Quality Checks
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request' || github.event.pull_request.draft == false || contains(github.event.pull_request.labels.*.name, 'ready_for_ci')
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          
      - name: Install linting dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black pylint
          
      - name: Lint with Black
        run: |
          black --check --verbose --config pyproject.toml installer src tests
          
      - name: PyLint
        run: |
          # Install minimal dependencies needed for pylint to work
          pip install -e .
          # Run pylint matching the PowerShell script configuration
          python -m pylint src/gaia --rcfile .pylintrc --disable C0103,C0301,W0246,W0221,E1102,R0401,E0401,W0718