# Copyright(C) 2024-2025 Advanced Micro Devices, Inc. All rights reserved.
# SPDX-License-Identifier: MIT

name: GAIA Installer Test

on:
  push:
    branches: ["main"]
    paths:
      - "installer/**"
      - "src/**"
      - "setup.py"
  pull_request:
    branches: ["main"]
    types: [opened, synchronize, reopened, ready_for_review]
    paths:
      - "installer/**"
      - "src/**"
      - "setup.py"
  merge_group:
  workflow_dispatch:

env:
  GAIA_INSTALL_PATH: "C:\\Users\\runneradmin\\AppData\\Local"
  GAIA_FULL_PATH: "C:\\Users\\runneradmin\\AppData\\Local\\GAIA"

jobs:
  build-installer:
    uses: ./.github/workflows/build_installer.yml

  gaia-installer-test:
    runs-on: windows-latest
    needs: build-installer
    if: github.event_name != 'pull_request' || github.event.pull_request.draft == false || contains(github.event.pull_request.labels.*.name, 'ready_for_ci')
    steps:
      - uses: actions/checkout@v4

      - name: Log build information
        shell: powershell
        run: |
          Write-Host "Using installer version: ${{ needs.build-installer.outputs.VERSION }}"
          Write-Host "Built from commit: ${{ needs.build-installer.outputs.COMMIT_HASH }}"
          Write-Host "Expected installer hash: ${{ needs.build-installer.outputs.INSTALLER_HASH }}"

      - name: Download GAIA Installer
        uses: actions/download-artifact@v4
        with:
          name: gaia-windows-installer-${{ needs.build-installer.outputs.VERSION }}-${{ needs.build-installer.outputs.COMMIT_HASH }}
          path: installer

      - name: Verify installer hash
        shell: powershell
        run: |
          $expectedHash = "${{ needs.build-installer.outputs.INSTALLER_HASH }}"
          $expectedCommitHash = "${{ needs.build-installer.outputs.COMMIT_HASH }}"
          $filePath = "installer\gaia-windows-setup.exe"
          $actualHash = (Get-FileHash -Path $filePath -Algorithm SHA256).Hash

          Write-Host "Expected hash: $expectedHash"
          Write-Host "Actual hash: $actualHash"
          Write-Host "Commit hash: $expectedCommitHash"

          if ($expectedHash -ne $actualHash) {
            Write-Host "Error: Hash mismatch! The downloaded installer does not match the built installer."
            Write-Host "This indicates that the wrong installer was downloaded or the installer was modified."
            exit 1
          } else {
            Write-Host "Hash verification successful: The downloaded installer matches the built installer."
          }

      - name: Test installer
        run: |
          cd installer
          .\RunInstaller.ps1 -INSTALL_PATH "${{ env.GAIA_INSTALL_PATH }}"
          if ($LASTEXITCODE -ne 0) {
            throw "Installer failed with exit code $LASTEXITCODE"
          }
