# Copyright(C) 2024 Advanced Micro Devices, Inc. All rights reserved.
# SPDX-License-Identifier: MIT

# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: GAIA UI Test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
    types: [opened, synchronize, reopened, ready_for_review]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  gaia-ui-test:
    runs-on: windows-latest
    if: github.event_name != 'pull_request' || github.event.pull_request.draft == false || contains(github.event.pull_request.labels.*.name, 'ready_for_ci')
    steps:
      - uses: actions/checkout@v3

      - name: Download and Install Miniconda
        shell: pwsh
        run: |
          Invoke-WebRequest -Uri "https://repo.anaconda.com/miniconda/Miniconda3-latest-Windows-x86_64.exe" -OutFile "miniconda.exe"
          Start-Process -FilePath "miniconda.exe" -ArgumentList "/S", "/D=$env:USERPROFILE\Miniconda3" -Wait

      - name: Initialize Conda
        shell: pwsh
        run: |
          Write-Host "Step 1: Add Conda to system PATH"
          $env:Path = "$env:USERPROFILE\Miniconda3;$env:USERPROFILE\Miniconda3\Scripts;$env:Path"
          [System.Environment]::SetEnvironmentVariable("Path", $env:Path, [System.EnvironmentVariableTarget]::Machine)

          Write-Host "Step 2: Initialize conda for both shells"
          & "$env:USERPROFILE\Miniconda3\Scripts\conda.exe" init powershell
          & "$env:USERPROFILE\Miniconda3\Scripts\conda.exe" init cmd.exe

          Write-Host "Step 3: Create the environment at system level"
          & "$env:USERPROFILE\Miniconda3\Scripts\conda.exe" create -n gaiaenv python=3.10 -y

      - name: Install dependencies
        shell: pwsh
        run: |
          Write-Host "Step 1: Activate conda environment"
          & "$env:USERPROFILE\Miniconda3\shell\condabin\conda-hook.ps1"
          conda activate gaiaenv

          Write-Host "Step 2: Install dependencies"
          python -m pip install --upgrade pip
          conda install pylint -y
          pip install -e .[dml,clip]

          Write-Host "Step 3: Verify installation"
          $gaiaPath = Get-Command gaia -ErrorAction SilentlyContinue
          if (-not $gaiaPath) {
            Write-Host "Error: gaia not installed correctly"
            Write-Host "Current PATH: $env:Path"
            exit 1
          }
          Write-Host "Found gaia at: $($gaiaPath.Source)"
          python -m pip check

      - name: Install Ollama
        shell: cmd
        run: |
          curl -L https://ollama.com/download/OllamaSetup.exe -o OllamaSetup.exe --progress-bar
          echo Ollama download complete. Starting installation.
          start /wait OllamaSetup.exe /VERYSILENT /SUPPRESSMSGBOXES /SP- /LOG="llama_install.log"
          echo "Ollama installation log:"
          type llama_install.log
          echo "PATH=C:\Users\runneradmin\AppData\Local\Programs\Ollama;%PATH%" >> $GITHUB_ENV
          del OllamaSetup.exe

      - name: Verify Ollama Installation
        shell: cmd
        run: |
          if exist "C:\Users\runneradmin\AppData\Local\Programs\Ollama\ollama.exe" (
              echo "Ollama installed successfully."
          ) else (
              echo "Ollama installation failed. Executable not found."
              exit 1
          )
          set PATH=%PATH%;C:\Users\runneradmin\AppData\Local\Programs\Ollama
          ollama --version

      - name: Ensure GAIA can open properly
        timeout-minutes: 10
        env:
          HUGGINGFACE_ACCESS_TOKEN: ${{ secrets.HUGGINGFACE_ACCESS_TOKEN }}
        uses: ./.github/actions/ui-testing
        with:
          username: "runneradmin"
          huggingface_access_token: ${{ secrets.HUGGINGFACE_ACCESS_TOKEN }}
          install_from_source: "true"
      
      
