# Copyright(C) 2024-2025 Advanced Micro Devices, Inc. All rights reserved.
# SPDX-License-Identifier: MIT

name: GAIA NPU Installer Test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
    types: [opened, synchronize, reopened, ready_for_review]
  workflow_dispatch:

jobs:
  build-installer:
    uses: ./.github/workflows/build_installer.yml

  gaia-npu-installer-test:
    runs-on: windows-latest
    if: github.event_name != 'pull_request' || github.event.pull_request.draft == false || contains(github.event.pull_request.labels.*.name, 'ready_for_ci')
    needs: build-installer
    steps:
      - uses: actions/checkout@v4

      - name: Download GAIA Installer
        uses: actions/download-artifact@v4
        with:
          name: gaia-windows-installer-${{ needs.build-installer.outputs.VERSION || 'latest' }}
          path: installer

      - name: Test installer with NPU mode
        run: |
          cd installer
          # Create a test directory
          mkdir -p test_install
          # Run installer with /MODE=NPU parameter
          .\gaia-windows-setup.exe /S /MODE=NPU /D=.\test_install
