# Copyright(C) 2024 Advanced Micro Devices, Inc. All rights reserved.

# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: GAIA Cli Pytest

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
    types: [opened, synchronize, reopened, ready_for_review]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  gaia-cli-pytest:
    runs-on: windows-latest
    if: github.event_name != 'pull_request' || github.event.pull_request.draft == false
    steps:
      - uses: actions/checkout@v3

      - name: Set up Miniconda with 64-bit Python
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniconda-version: "latest"
          activate-environment: gaia
          python-version: "3.10"

      - name: Install dependencies
        shell: bash -el {0}
        run: |
          python -m pip install --upgrade pip
          conda install pylint
          pip install -e .[pytest]
          python -m pip check

      - name: PyLint
        shell: bash -el {0}
        run: |
          pylint src/gaia --rcfile .pylintrc --disable C0103,C0301,W0246,W0221,E1102,R0401,E0401,W0718

      - name: Install Ollama
        shell: cmd
        run: |
          curl -L https://ollama.com/download/OllamaSetup.exe -o OllamaSetup.exe --progress-bar
          echo Ollama download complete. Starting installation.
          start /wait OllamaSetup.exe /VERYSILENT /SUPPRESSMSGBOXES /SP- /LOG="llama_install.log"
          echo "Ollama installation log:"
          type llama_install.log
          echo "PATH=C:\Users\runneradmin\AppData\Local\Programs\Ollama;%PATH%" >> $GITHUB_ENV
          del OllamaSetup.exe

      - name: Verify Ollama Installation
        shell: cmd
        run: |
          if exist "C:\Users\runneradmin\AppData\Local\Programs\Ollama\ollama.exe" (
              echo "Ollama installed successfully."
          ) else (
              echo "Ollama installation failed. Executable not found."
              exit 1
          )
          set PATH=%PATH%;C:\Users\runneradmin\AppData\Local\Programs\Ollama
          ollama --version

      - name: Test GAIA
        timeout-minutes: 10
        shell: bash -el {0}
        env:
          HUGGINGFACE_ACCESS_TOKEN: ${{ secrets.HUGGINGFACE_ACCESS_TOKEN }}
          HF_TOKEN: ${{ secrets.HUGGINGFACE_ACCESS_TOKEN }}
        run: |
          python tests/test_gaia.py
