# Copyright(C) 2024 Advanced Micro Devices, Inc. All rights reserved.
# SPDX-License-Identifier: MIT

name: GAIA Installer Test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
    types: [opened, synchronize, reopened, ready_for_review]
  workflow_dispatch:

jobs:
  gaia-installer-test:
    runs-on: windows-latest
    if: github.event_name != 'pull_request' || github.event.pull_request.draft == false || contains(github.event.pull_request.labels.*.name, 'ready_for_ci')
    steps:
      - uses: actions/checkout@v4

      - name: Install NSIS
        run: |
          # Download NSIS installer
          curl -L -o nsis.exe https://sourceforge.net/projects/nsis/files/NSIS%203/3.10/nsis-3.10-setup.exe
          
          # Install NSIS
          Start-Process nsis.exe -ArgumentList '/S' -Wait

      - name: Verify NSIS installation
        run: |
          # Check if NSIS is installed
          & 'C:\Program Files (x86)\NSIS\makensis.exe' /VERSION

      - name: Build the GAIA installer
        run: |
          cd installer
          & 'C:\Program Files (x86)\NSIS\makensis.exe' 'Installer.nsi'

          if (Test-Path "GAIA_Installer.exe") {
            Write-Host "GAIA_Installer.exe has been created successfully."
          } else {
            Write-Host "GAIA_Installer.exe was not found."
            exit 1
          }

      - name: Install Ollama
        shell: cmd
        run: |
          curl -L https://ollama.com/download/OllamaSetup.exe -o OllamaSetup.exe --progress-bar
          echo Ollama download complete. Starting installation.
          start /wait OllamaSetup.exe /VERYSILENT /SUPPRESSMSGBOXES /SP- /LOG="llama_install.log"
          echo "Ollama installation log:"
          type llama_install.log
          echo "PATH=C:\Users\runneradmin\AppData\Local\Programs\Ollama;%PATH%" >> $GITHUB_ENV
          del OllamaSetup.exe

      - name: Verify Ollama Installation
        shell: cmd
        run: |
          if exist "C:\Users\runneradmin\AppData\Local\Programs\Ollama\ollama.exe" (
              echo "Ollama installed successfully."
          ) else (
              echo "Ollama installation failed. Executable not found."
              exit 1
          )
          set PATH=%PATH%;C:\Users\runneradmin\AppData\Local\Programs\Ollama
          ollama --version

      - name: Attempt to install GAIA using installer
        shell: cmd
        run: |
          echo "Having issues debugging the installer? Check the installer README for tips on how to do that."
          set PATH=%PATH%;C:\Users\runneradmin\AppData\Local\Programs\Ollama
          cd installer
          GAIA_Installer.exe /S

      - name: Ensure GAIA can open properly
        timeout-minutes: 10
        env:
          HUGGINGFACE_ACCESS_TOKEN: ${{ secrets.HUGGINGFACE_ACCESS_TOKEN }}
        uses: ./.github/actions/ui-testing
        with:
          username: "runneradmin"
          huggingface_access_token: ${{ secrets.HUGGINGFACE_ACCESS_TOKEN }}
          install_from_source: "false"
          
      - name: Upload Installer
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: GaiaInstaller
          path: |
            installer\GAIA_Installer.exe
