# Copyright(C) 2024-2025 Advanced Micro Devices, Inc. All rights reserved.
# SPDX-License-Identifier: MIT

name: GAIA Installer Test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
    types: [opened, synchronize, reopened, ready_for_review]
  workflow_dispatch:

jobs:
  build-installer:
    uses: ./.github/workflows/build_installer.yml

  gaia-installer-test:
    runs-on: windows-latest
    if: github.event_name != 'pull_request' || github.event.pull_request.draft == false || contains(github.event.pull_request.labels.*.name, 'ready_for_ci')
    needs: build-installer
    steps:
      - uses: actions/checkout@v4

      - name: Download GAIA Installer
        uses: actions/download-artifact@v4
        with:
          name: gaia-windows-installer-${{ needs.build-installer.outputs.VERSION || 'latest' }}
          path: installer

      - name: Install Ollama
        shell: cmd
        run: |
          curl -L https://ollama.com/download/OllamaSetup.exe -o OllamaSetup.exe --progress-bar
          echo Ollama download complete. Starting installation.
          start /wait OllamaSetup.exe /VERYSILENT /SUPPRESSMSGBOXES /SP- /LOG="llama_install.log"
          echo "Ollama installation log:"
          type llama_install.log
          echo "PATH=C:\Users\runneradmin\AppData\Local\Programs\Ollama;%PATH%" >> $GITHUB_ENV
          del OllamaSetup.exe

      - name: Verify Ollama Installation
        shell: cmd
        run: |
          if exist "C:\Users\runneradmin\AppData\Local\Programs\Ollama\ollama.exe" (
              echo "Ollama installed successfully."
          ) else (
              echo "Ollama installation failed. Executable not found."
              exit 1
          )
          set PATH=%PATH%;C:\Users\runneradmin\AppData\Local\Programs\Ollama
          ollama --version

      - name: Attempt to install GAIA using installer
        shell: cmd
        run: |
          echo "Having issues debugging the installer? Check the installer README for tips on how to do that."
          set PATH=%PATH%;C:\Users\runneradmin\AppData\Local\Programs\Ollama
          cd installer
          gaia-setup.exe /S /MODE=GENERIC

      - name: Ensure GAIA can open properly
        timeout-minutes: 10
        env:
          HUGGINGFACE_ACCESS_TOKEN: ${{ secrets.HUGGINGFACE_ACCESS_TOKEN }}
          QT_QPA_PLATFORM: "offscreen"
          QTWEBENGINE_DISABLE_SANDBOX: "1"
          QT_QPA_FONTDIR: "/usr/share/fonts"
          # Ignore Qt warnings
          QT_LOGGING_RULES: "qt.qpa.fonts.warning=false;qt.core.qmetaobject.warning=false"
        uses: ./.github/actions/ui-testing
        with:
          username: "runneradmin"
          huggingface_access_token: ${{ secrets.HUGGINGFACE_ACCESS_TOKEN }}
          install_from_source: "false"
