# Copyright(C) 2024 Advanced Micro Devices, Inc. All rights reserved.

name: GAIA NPU Installer Test

on:
  push:
    branches: ["main"]
    paths-ignore:
      - 'docs/**'
      - 'data/**'
      - 'notebooks/**'
  pull_request:
    branches: ["main"]
    types: [opened, synchronize, reopened, ready_for_review]
    paths-ignore:
      - 'docs/**'
      - 'data/**'
      - 'notebooks/**'
  workflow_dispatch:

jobs:
  gaia-npu-installer-test:
    runs-on: windows-latest
    if: github.event_name != 'pull_request' || github.event.pull_request.draft == false
    steps:
      - uses: actions/checkout@v4

      - name: Install NSIS
        run: |
          # Download NSIS installer
          curl -L -o nsis.exe https://sourceforge.net/projects/nsis/files/NSIS%203/3.10/nsis-3.10-setup.exe
          
          # Install NSIS
          Start-Process nsis.exe -ArgumentList '/S' -Wait

      - name: Verify NSIS installation
        run: |
          # Check if NSIS is installed
          & 'C:\Program Files (x86)\NSIS\makensis.exe' /VERSION

      - name: Build the GAIA installer for NPU
        run: |
          cd installer
          & 'C:\Program Files (x86)\NSIS\makensis.exe' 'Installer.nsi'

          if (Test-Path "GAIA_Installer.exe") {
            Write-Host "GAIA_Installer.exe has been created successfully."
          } else {
            Write-Host "GAIA_Installer.exe was not found."
            exit 1
          }
